[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-C", "link-arg=-Tkernel.lds",      # Add linker script
    "-C", "opt-level=0",                # Don't optimize
]

[build]
target = "riscv64gc-unknown-none-elf"